	ORG 0000H
	JMP MAIN
	ORG 0023H
	JMP INTERRUPT
	ORG 0050H
MAIN:
	MOV TMOD, #00100000B	;Timer 1,Mode 2
	MOV TL1, #0E6H			;Baud rate = 2400
	MOV TH1, #0E6H			;初始值 E6H = 230
	ORL PCON, #80H			;SMOD = 1
	SETB TR1				;Timer Run
	SETB ES
	CLR TI
	CLR RI
	SETB EA 				;開啟中斷
	SETB PS
	CLR SM2
	CLR SM0					;Serial port Mode 1
	SETB SM1
	SETB REN

INTERRUPT:
	JB TI, LOOP
	JNB RI, INTERRUPT
	CLR RI
	MOV A, SBUF				;將接收到的東西存到A
	CALL LOOP
	RETI

LOOP:
	CLR TI
	ADD A, #20H				;轉成小寫(ASCII要減20H)
	MOV SBUF, A				;將A的值傳給發送SBUF
	JNB TI, $ 				;沒有發送就跳回自己(LOOP)
	CALL DELAY
	RET

DELAY:
	MOV R6, #50
DELAY1:
	MOV R7, #50
DELAY2:
	DJNZ R7, DELAY2
	DJNZ R6, DELAY1
	RET
END
